## Ejercicios de Numpy - parte 2

In [1]:
import numpy as np

## Ejercicio 1
Genera un array que contenga 25 elementos entre 0 y 99 siguiendo una distribución lineal. Luego, transforma ese array en una matriz de 5 x 5. ¿Cuál es la diagonal de la matriz? ¿Y la diagonal justo superior?

In [63]:
a1=np.linspace(start=0, stop=100, num=25, endpoint=False)
a1

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [64]:
# Matriz 5x5
a1=a1.reshape((5,5))
print(a1, a1.shape)


[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]] (5, 5)


In [65]:
# Diagonal
np.diag(a1)

array([ 0., 24., 48., 72., 96.])

In [66]:
# Diagonal superior
np.diag(a1, 1)


array([ 4., 28., 52., 76.])

## Ejercicio 2

Crea un array de 5 x 4 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir dos nuevas matrices, una de  5 x 9, y otra de 9 x 5.





$m = \begin{pmatrix}
0 & 4 & 8 & 12 & 16 \\
20 & 24 & 28 & 32 & 36 \\
40 & 44 & 48 & 52 & 56 \\
60 & 64 & 68 & 72 & 76 \\
80 & 84 & 88 & 92 & 96
\end{pmatrix}$
$m2 = \begin{pmatrix}
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5
\end{pmatrix}$

In [67]:
a2=np.full(shape=(4,5),fill_value=10)
a2

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [68]:
# 9x5
m=np.concatenate((a1,a2), axis=0)
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [69]:
# 5x9
m2=m.reshape((5,9))
m2


array([[ 0.,  4.,  8., 12., 16., 20., 24., 28., 32.],
       [36., 40., 44., 48., 52., 56., 60., 64., 68.],
       [72., 76., 80., 84., 88., 92., 96., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

## Ejercicio 3

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array: 
    
array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?

In [121]:
a3=np.array(['      este es un curso de openwebinars     '])
a3

array(['      este es un curso de openwebinars     '], dtype='<U43')

In [122]:
a3=np.char.strip(a3)
a3


array(['este es un curso de openwebinars'], dtype='<U43')

In [123]:
a3=np.char.split(a3, sep=' ')
a3=np.array(a3[0]) # Paca convertir el array de listas en un array normal
a3

array(['este', 'es', 'un', 'curso', 'de', 'openwebinars'], dtype='<U12')

In [124]:
a3=np.char.capitalize(a3)
a3

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

In [125]:
a3[np.char.startswith(a3, prefix='E')]

array(['Este', 'Es'], dtype='<U12')

## Ejercicio 4

Considerando las matrices A y B. 

$A = \begin{pmatrix}
3 & 1 & 2 \\
4 & 1 & 3 \\
2 & 0 & 1
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 0 & 3 \\
1 & 1 & 1 \\
0 & 2 & 4
\end{pmatrix}$

- Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?
- Realiza la multiplicación de la matriz A x 2
- ¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [130]:
m=np.array([[3,1,2],[4,1,3],[2,0,1]])
m2=np.array([[2,0,3],[1,1,1],[0,2,4]])
print(m, '\n \n', m2)

[[3 1 2]
 [4 1 3]
 [2 0 1]] 
 
 [[2 0 3]
 [1 1 1]
 [0 2 4]]


In [50]:
# Multiplicación matricial
np.dot(m,m2) 

array([[ 7,  5, 18],
       [ 9,  7, 25],
       [ 4,  2, 10]])

In [51]:
np.dot(m2,m) 

array([[12,  2,  7],
       [ 9,  2,  6],
       [16,  2, 10]])

In [52]:
# Multiplicar por 2
np.dot(m,2)

array([[6, 2, 4],
       [8, 2, 6],
       [4, 0, 2]])

In [54]:
# Producto escalar
np.vdot(m, m2)

24

In [55]:
np.vdot(m2, m)


24

## Ejercicio 5

Usando la matriz A del ejercicio anterior, calcula:

- A^3
- El determinante de A
- Resuelve la ecuación Ax = y, siendo ***y*** el array [3,2,5]

In [131]:
# A^3
np.linalg.matrix_power(m,3)

array([[ 89,  21,  57],
       [114,  27,  73],
       [ 42,  10,  27]])

In [132]:
# Determinante de A
np.linalg.det(m)

1.0

In [135]:
# Ecuación
y=np.array([3,2,5])
np.linalg.solve(m,y)

array([ 6., -1., -7.])